# Mohit Kumar Rauniyar [BL.EN.U4CSE22089]
### Lab_02

In [81]:
import pandas as pd
import numpy as np
import statistics

In [16]:
df = pd.read_excel('./Lab Session Data.xlsx', sheet_name=None)
purchase_data = df['Purchase data'].iloc[:, :5]
purchase_data.head(10)

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

In [48]:
matrix_A = np.array(purchase_data.iloc[:, 1:4])
matrix_C = np.array(purchase_data.iloc[:, 4:])
matrix_C.reshape(10,1)
print(matrix_A)
print(matrix_C)


[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]


In [49]:
print(matrix_A.shape)
print(matrix_C.shape)

(10, 3)
(10, 1)


In [47]:
rank_A = np.linalg.matrix_rank(matrix_A)
rank_C = np.linalg.matrix_rank(matrix_C)
print(rank_A)
print(rank_C)

3
1


In [52]:
A_inv = np.linalg.pinv(matrix_A)
print(A_inv)

[[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]


In [60]:
cost_of_each_product = np.matmul(A_inv, matrix_C)
cost_of_each_product

array([[ 1.],
       [55.],
       [18.]])

In [66]:
model_X = pd.DataFrame({'Product': ['Candies (#)', 'Mangoes (Kg)','Milk Packets (#)'], 'Cost': np.ndarray.tolist(cost_of_each_product.ravel())})
model_X

Product  Cost
0       Candies (#)   1.0
1      Mangoes (Kg)  55.0
2  Milk Packets (#)  18.0

In [59]:
purchase_data['Status'] = ['Rich' if x > 200 else 'Poor' for x in purchase_data['Payment (Rs)']]
purchase_data

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) Status
0      C_1           20             6                 2           386   Rich
1      C_2           16             3                 6           289   Rich
2      C_3           27             6                 2           393   Rich
3      C_4           19             1                 2           110   Poor
4      C_5           24             4                 2           280   Rich
5      C_6           22             1                 5           167   Poor
6      C_7           15             4                 2           271   Rich
7      C_8           18             4                 2           274   Rich
8      C_9           21             1                 4           148   Poor
9     C_10           16             2                 4           198   Poor

In [67]:
irctc_data = df['IRCTC Stock Price']
irctc_data

Date Month  Day    Price     Open     High      Low   Volume  \
0    Jun 29, 2021   Jun  Tue  2081.85  2092.00  2126.90  2065.05    1.67M   
1    Jun 28, 2021   Jun  Mon  2077.75  2084.00  2112.45  2068.40  707.73K   
2    Jun 25, 2021   Jun  Fri  2068.85  2084.35  2088.50  2053.10  475.82K   
3    Jun 24, 2021   Jun  Thu  2072.95  2098.00  2098.00  2066.00  541.51K   
4    Jun 23, 2021   Jun  Wed  2078.25  2102.00  2111.40  2072.00  809.62K   
..            ...   ...  ...      ...      ...      ...      ...      ...   
244  Jul 07, 2020   Jul  Tue  1397.40  1410.00  1411.00  1390.05  480.21K   
245  Jul 06, 2020   Jul  Mon  1400.75  1405.50  1415.50  1394.00  614.93K   
246  Jul 03, 2020   Jul  Fri  1405.10  1415.00  1425.00  1398.00  599.49K   
247  Jul 02, 2020   Jul  Thu  1412.35  1440.00  1467.80  1395.30    2.16M   
248  Jul 01, 2020   Jul  Wed  1363.05  1363.65  1377.00  1356.00  383.00K   

       Chg%  
0    0.0020  
1    0.0043  
2   -0.0020  
3   -0.0026  
4   -0.0023  
..      ...  
244 -0.0024  
245 -0.0031  
246 -0.0051  
247  0.0362  
248  0.0032  

[249 rows x 9 columns]

In [82]:
Price_mean = statistics.mean(irctc_data['Price'])
Price_mean

1560.663453815261

In [83]:
price_variance = statistics.variance(irctc_data['Price'])
price_variance

58732.365352539186

In [98]:
filter = irctc_data['Day'] == 'Wed'
day_data = irctc_data.where(filter, inplace = False)
day_data.dropna(inplace=True)
day_data_mean = statistics.mean(day_data['Price'])
day_data_mean


1550.706